DROP TABLE IF EXISTS clientes;

CREATE TABLE clientes (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    peso FLOAT NOT NULL,
    objetivo VARCHAR(50) NOT NULL,
    frequenciaMusculacao INT NOT NULL,
    percentualGordura INT,
    proteinaDiaria INT
)